### ISSUE TITLE
Definir estetica del sitio

### ISSUE THREAD

**Issue by FrancoTrivini** [pilCbaNet/fsnet6-team6#1]
Se debe definir la estética general de todo el sitio, para poder generar el boceto.

**Comment by rollanes** [comment]
![Image](https://user-images.githubusercontent.com/98404125/193944847-744f604f-b167-4d0f-aca4-a6ae17529ea2.jpg)

**Comment by FrancoTrivini** [comment]
Definimos que esta va a ser la estética de nuestro exchanges.

**Comment by FrancoTrivini** [comment]
Definimos que esta va a ser la estética de nuestro exchanges.

**Comment by FrancoTrivini** [comment]
Definimos que esta va a ser la estética de nuestro exchanges.

**Comment by FrancoTrivini** [comment]
Definimos que esta va a ser la estética de nuestro exchanges.

**Comment by FrancoTrivini** [comment]
Definimos que esta va a ser la estética de nuestro exchanges.

**Comment by FrancoTrivini** [comment]
Definimos que esta va a ser la estética de nuestro exchanges.
